name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # atualiza a cada hora
  workflow_dispatch:      # permite rodar manualmente

jobs:
  update-readme:
    name: Atualizar README com dados do WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
